#discovery.server: 192.168.1.253:8848
#discovery.group: dev
#discovery.namespace: 99d1c138-af0e-4ccd-82f7-7a58d917ce96
##discovery.username: zkzx1
##discovery.password: zkzx6661
##-------------------------------
#config.server: 192.168.1.253:8848
#config.group: dev
#config.namespace: 99d1c138-af0e-4ccd-82f7-7a58d917ce96
##config.username: zkzx1
##config.password: zkzx6661